import { useState } from 'react'
import { Activity, ArrowRight, BookOpen, Database, FileCode2, GitBranch, Lock, Server, UserRound } from 'lucide-react'

const stages = [
  { id: 'client', title: 'Client and IDE', icon: UserRound, detail: 'PyCharm, Rider, VS Code, or Copilot CLI creates the request. The client remains responsible for authentication and model selection.', data: 'Prompt, conversation history, repository context, tool calls, model, IDE metadata' },
  { id: 'intercept', title: 'Local interception', icon: Server, detail: 'The HTTPS bridge receives GitHub Copilot traffic on localhost:8767. TLS is terminated by the locally trusted mitmproxy certificate.', data: 'Host, path, headers, request timing, raw JSON payload' },
  { id: 'shape', title: 'Context shaper', icon: Activity, detail: 'TrimP classifies each safe text field and selects JSON, chat, code, search, bash, tool-output, or prompt compression.', data: 'Before/after estimates, algorithm, field path, change reason, savings' },
  { id: 'upstream', title: 'GitHub Enterprise', icon: GitBranch, detail: 'The optimized request is forwarded with the client Copilot authentication. Protocol state, encrypted reasoning, and protected instructions stay intact.', data: 'Actual input, cached input, output, total tokens, AIU, response latency' },
  { id: 'trace', title: 'Trace and dashboard', icon: Database, detail: 'Original and optimized bodies, model usage, repository, IDE, branch, debug excerpts, and recommendations are written to the local SQLite audit trail.', data: 'Conversation timeline, quality signals, cost estimate, recommendations, health status' },
]

export default function SystemDesign() {
  const [selected, setSelected] = useState('shape')
  const active = stages.find(stage => stage.id === selected) || stages[2]
  const ActiveIcon = active.icon
  const releaseNotes = ['1.0.0', 'GitHub Enterprise short-lived token exchange', 'OpenAI chat and Responses-compatible proxy routes', 'PyCharm and Rider HTTPS interception bridge', 'Full request, optimized request, response, and usage tracing', 'Repository, branch, IDE, model, and local-time attribution', 'Compression scoring, recommendations, and cost estimates', 'Live service health and destructive database controls', 'Quality signals for compression, context, routing, loops, and cache health'].join('\n- ')
  return <main className="system-page">
    <header className="system-page-header"><img className="trimp-system-logo" src="/trimpilot-logo.png" alt="Trim-Pilot" /><div className="optimizer-kicker"><BookOpen size={15} /> Design document</div><h1>Trim-Pilot (TrimP) System & Developer Guide</h1><p>Architecture, ownership, data flow, safety boundaries, and the evidence trail behind every token decision.</p></header>
    <section className="system-release-strip"><span>Trim-Pilot · release 1.0.0</span><b>Enterprise proxy observability</b><span>GitHub Copilot Enterprise runtime</span></section>
    <section className="system-flow"><div className="section-heading"><div><h2>End-to-end data flow</h2><p>Select a stage to inspect what enters, what happens, and what is recorded.</p></div><Lock size={18} /></div><div className="flow-track">{stages.map((stage, index) => { const Icon = stage.icon; return <div className="flow-step-wrap" key={stage.id}><button className={`flow-step ${selected === stage.id ? 'selected' : ''}`} onClick={() => setSelected(stage.id)}><Icon size={18} /><b>{stage.title}</b></button>{index < stages.length - 1 && <ArrowRight className="flow-arrow" size={17} />}</div> })}</div><div className="flow-detail"><div className="flow-detail-title"><ActiveIcon size={19} /><b>{active.title}</b></div><p>{active.detail}</p><div className="data-chip"><span>Observed data</span><b>{active.data}</b></div></div></section>
    <section className="system-doc-grid"><article><FileCode2 size={18} /><h3>Compression contract</h3><p>TrimP deep-copies the request, estimates tokens, rewrites only understood text fields, preserves protocol structures, and forwards the optimized body. Every change is recorded by JSON path.</p><code>tokens_saved = estimate(before) - estimate(after)</code></article><article><Database size={18} /><h3>Evidence model</h3><p>SQLite stores the original body, optimized body, response, actual usage, algorithm details, repository, branch, client, timestamps, debug context, grade, and recommendations.</p><code>estimated savings != GitHub billed usage</code></article><article><Lock size={18} /><h3>Safety boundaries</h3><p>System prompts, encrypted reasoning, function-call protocol state, and item references are protected by default. Cache alignment matters because shortening stable prefixes can reduce cache reuse.</p><code>optimize safe context, preserve control state</code></article><article><Activity size={18} /><h3>Operational loop</h3><p>Health checks run continuously for the dashboard, BYOK proxy, HTTPS bridge, and configured IDEs. Failures surface on the main page with a suggested recovery action.</p><code>capture → shape → forward → measure → explain</code></article></section>
    <section className="developer-log-section"><div className="section-heading"><div><h2>Developer log and release notes</h2><p>Trackable implementation record for the current release.</p></div></div><pre>{releaseNotes}</pre></section>
    <footer className="developer-mini-footer"><div className="developer-avatar small">NR</div><div><b>About the developer</b><span>Nabiha Raza · Trim-Pilot system design and enterprise observability</span></div><span className="developer-version">v1.0.0</span></footer>
  </main>
}
